### ISSUE TITLE
CallApi function implementation and logic

### ISSUE THREAD

**Issue by sinukaarel** [sendsmaily/smaily-magento-extension#17]
Current CallAPi function implementation could be improved.

https://github.com/sendsmaily/smaily-magento-extension/blob/41e88459a68e7fff598acffd202cab6865cc238f/Helper/Data.php#L422

I think that the response message should be implemented as before - with error messages outputed in callApi response array. That makes error logging in various other methods easier ( especially if you want to log different calling funtions in different files). Also i think it should output curl response-status code in response array for displaying different error messages based on status-code. This message generation based of response code could be also done in callAPi function in validation section ( catch block maybe)

Error messages from api call could be also visualised in front end in refrence in this issue #15 for improving user experience.

https://github.com/sendsmaily/smaily-magento-extension/blob/41e88459a68e7fff598acffd202cab6865cc238f/Helper/Data.php#L447-L453

Current api call validation is only implemented in POST methods elseif block.

**Comment by ram4nd** [comment]
I would like to add that, legacy api errors work separately from http status codes. You might get 200, even when there is an error, see [http://help.smaily.com/en/support/solutions/articles/16000018661-possible-results](http://help.smaily.com/en/support/solutions/articles/16000018661-possible-results). So in order to improve the error logging, both http status codes and legacy codes have to be implemented.

**Comment by sinukaarel** [comment]
Implementing old method when response is empty when there is error and `callApi `function is logging error messages. You can log general error message in functions that are using `callApi `function and check for specific reasons in log generated by `callApi`.
#15 issue is handled with backend model.
